### ISSUE TITLE
Refatorar #8

### ISSUE THREAD

**Issue by samicoluiz** [MaxJuniorr/trab_expressao_regulares#10]
Refatorar #8 utilizando uma função de ordem superior (função que recebe ou retorna outra função) ou classe abstrata para criar um construtor de strings de teste.

```python
def gerador(sequencia, da, linguagem, aceita):
    def gerar_arranjo(n):
        ...
        return "".join(sequencia, da, linguagem, aceita)
    return gerar_arranjo
```

A função de ordem superior deve gerar uma função de primeira ordem que vai gerar uma string de tamanho `n` com os padrões escolhidos.

```python
casais_hetero_ultimos_3_h = gerador(casais_hetero, fecho_reflex_transit_hm, final_h(3))
casais_hetero_ultimos_3_h(200)
# Output:
# MHhhmmmhhmhmhhhmmhmmmhmmhhhhmmhhmmhhhhhhhhhmmhmmhmhhhhmhhhmmmmmhmhhhmmmmhhhhhmhmmmmmhmhhmhhmhhhmhmmmhmmhmhhmhhmmhhmhmhhmhmhmmmmmhmhhhhmhmhhmhhmhmhmhhmmhhmhmhmmhhhmhmmhmhhhhhmhmmhhhmmhhmhmhmmmmmmhmhmmhhh
```

Lembrando que esses códigos são meramente exemplos ilustrativos podendo necessitar de refinamento conceitual não estando prontos de maneira alguma para ser implementados no estado em que aparecem neste comentário.

**Comment by MaxJuniorr** [comment]
A cadeia que esse gerador deve gerar tem que ser aleatória, seguindo os padrões solicidado, certo?
Ou seja, a cada nova chamada, mesmo com o n igual, uma nova cadeia pode ser gerada.
