### ISSUE TITLE
ajustar as funcoes floor e ceil

### ISSUE THREAD

**Issue by samicoluiz** [MaxJuniorr/trab_expressao_regulares#13]

**Comment by samicoluiz** [comment]
@MaxJuniorr Eu tava pensando o seguinte, no nosso código atualmente existem 3 tipos diferentes de regras e cada uma tem a sua peculiaridade:
1. Regras dos pais, cuja peculiaridade é não permitir cumulação com outras regras de pais, por isso são únicas.
2. Regras de limite (ou como queira chamar floor e ceiling) cuja peculiaridade é exigir mais de 1 parâmetro.
3. Regras de prole, que são o "padrão", podem ser cumuladas e só exigem um parâmetro.

Cada tipo desse vai precisar ser contemplado na assinatura da função geradora. Isso foi a conclusão que chegamos ontem, nada de novo, só organizando as ideias.

Além disso, nós precisamos incorporar uma maneira de realizar cumulacao do tipo OR que vai ser usado quando ouver cumulação de regras de prole. Talvez uma outra função que pegue as possibilidades de funções geradas e escolha uma aleatoriamente.

**Comment by MaxJuniorr** [comment]
# Tarefa resolvida no commit: ee11d7c898f8b0f0b6a367e06f3d11a71f765a14

## Atenção:
Somente as funções floor foram adaptadas. Após pensar um pouco, concluí que as funções ceil não precisavam ser altaradas, já que o vazio é permitido nesse caso.
